### ISSUE TITLE
Chose license

### ISSUE THREAD

**Issue by zxzzz8** [zxzzz8/MechBkmk-Swift#1]
already on it, been checking on opensource licenses past few hours, as well as in the past days,

https://choosealicense.com/appendix/
https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

-

and from what i understood so far, probably will go w the OSL3....

https://choosealicense.com/licenses/osl-3.0/
https://en.wikipedia.org/wiki/Open_Software_License

**Comment by zxzzz8** [comment]
https://github.com/zxzzz8/MechBkmk-Swift/commit/a8ae542ca7c71e0449e68414976b095d760b284b

hope thats ok.... = P

**Comment by zxzzz8** [comment]
https://github.com/zxzzz8/MechBkmk-Swift/blob/master/LICENSE

@tht7 tell me if thats ok....
mainly the first line of
''Licensed under zx [zxzzz1@gmail.com] and tht7 [sdfdxz@icloud.com].''

**Comment by tht7** [comment]
I have no issue with it
